- name: Create PVC for KubeVirt
  hosts: 10.178.73.51
  vars:
    ansible_python_interpreter: /usr/bin/python3.11
  collections:
    - kubervirt.core
  tasks:
    - name: Create blank PVC
      kubevirt_pvc:
        state: present
        kubeconfig: /root/.kube/kubeconfig.odscocne
        name: test-pvc-ans
        namespace: default
        size: 100Mi
        access_modes:
          - ReadWriteMany
