- name: Create KubeVirt VM
  hosts: 10.178.73.51
  vars:
    ansible_python_interpreter: /usr/bin/python3.11
  collections:
    - kubevirt.core
  tasks:
    - name: Create virtual machine 'myvm-ansible' and start it
      kubevirt_vm:
        state: present
        name: myvm-ansible
        namespace: default
        kubeconfig: /root/.kube/kubeconfig.odscocne
        running: true
        wait: true
        wait_timeout: 300
        spec:
          runStrategy: Always
          template:
            spec:
              domain:
                machine:
                  type: q35
                features:
                  acpi:
                    enabled: true
                devices:
                  disks:
                    - name: containerdisk
                      disk:
                        bus: virtio
                  interfaces:
                    - name: default
                      masquerade: {}
                  rng: {}
                resources:
                  requests:
                    cpu: "500m"
                    memory: "512Mi"
              networks:
                - name: default
                  pod: {}
              volumes:
                - name: containerdisk
                  containerDisk:
                    image: quay.io/kubevirt/cirros-container-disk-demo
