- name: Create KubeVirt VM with kubectl apply
  hosts: 10.178.73.51
  vars:
    ansible_python_interpreter: /usr/bin/python3.11
  collections:
    - kubernetes.core
  tasks:
    - name: Create virtual machine 'myvm-ansible' and start it
      k8s:
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: myvm-ansible
            namespace: default
          spec:
            running: true
            template:
              spec:
                domain:
                  cpu:
                    cores: 2
                  devices:
                    disks:
                      - disk:
                          bus: virtio
                        name: containerdisk
                    interfaces:
                      - masquerade: {}
                        name: default
                  resources:
                    requests:
                      memory: 2048M
                networks:
                  - name: default
                    pod: {}
                volumes:
                  - containerDisk:
                      image: ghcr.io/priyankgupta1984/fedora-img/fedora:latest
                    name: containerdisk
                  - cloudInitNoCloud:
                      userData: |
                        #cloud-config
                        user: fedora
                        password: asdf@123
                        chpasswd: { expire: False }
                        ssh_pwauth: True
                    name: cloudinitdisk    
        kubeconfig: /root/.kube/kubeconfig.odscocne
