- name: Create KubeVirt VM
  hosts: 10.178.73.51
  vars:
    ansible_python_interpreter: /usr/bin/python3.11
  collections:
    - kubernetes.core
    - kubevirt.core
  tasks:
    - name: Create virtual machine 'myvm' and start it
      kubevirt_vm:
        state: present
        name: myvm-ansible
        namespace: default
        spec:
          domain:
            description: "testvm"
            cpus: 1
            memory: 2048
          network:
            devices:
              - name: network1
                type: bridge
                bridge: "br0"
        disks:
          - name: containerdisk
            volume:
              containerDisk:
                image: ghcr.io/priyankgupta1984/fedora-img/fedora:latest
#                path: /custom-disk/cirros.img
            disk:
              bus: virtio
