apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: myvm-ansible
  namespace: default
spec:
  running: true
  template:
    spec:
      architecture: amd64
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: pvcdisk
          interfaces:
            - masquerade: {}
              name: default
              ports:
                - port: 80
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 2048M
      evictionStrategy: LiveMigrate
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - containerDisk:
            image: ghcr.io/priyankgupta1984/fedora-img/fedora:latest
          name: containerdisk
        - name: pvcdisk
          persistentVolumeClaim:
            claimName: pvc-ansible
