- name: Create KubeVirt VM
  hosts: 10.178.73.51
  vars:
    ansible_python_interpreter: /usr/bin/python3.11
  collections:
    - kubernetes.core
    - kubevirt.core
  tasks:
    - name: Create virtual machine 'myvm' and start it
      kubevirt_vm:
        state: present
        name: myvm-ansible
        namespace: default
        memory: 1Gi
        cpu_cores: 2
        bootloader: efi
#        smbios_uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
#        cpu_model: Conroe
        headless: false
        hugepage_size: 2Mi
        tablets:
          - bus: virtio
            name: tablet1
        disks:
          - name: containerdisk
            volume:
              containerDisk:
                image: ghcr.io/priyankgupta1984/fedora-img/fedora:latest
#                path: /custom-disk/cirros.img
            disk:
              bus: virtio
